version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bioinspired_postgres
    environment:
      POSTGRES_DB: bioinspired
      POSTGRES_USER: bioinspired_user
      POSTGRES_PASSWORD: bioinspired_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
